name: Alena CI/CD Pipeline 

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4
      
      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Устанавливаем тестовый фреймворк
         
      - name: Запуск калькулятора +
        run: python Calc.py 5 + 4
      
      - name: Запуск калькулятора -
        run: python Calc.py 6 - 4

      - name: Запуск калькулятора /
        run: python Calc.py 30 / 5
  
      - name: Запуск тестов
        run: pytest test_calc.py
        
  create_pull_request:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Отключаем встроенные учетные данные

      - name: Настройка аутентификации Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      
      - name: Создание Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: development
          base: main
          title: 'Автоматическое слияние изменений из development в main'
          body: 'Этот PR содержит последние исправления и обновления.'
          labels: 'авто-слияние'
          draft: false
          
  merge_pull_request:
    needs: create_pull_request
    runs-on: ubuntu-latest
    steps:
       - name: Pull Request Automerge
         if: steps.cpr.outputs.pull-request-operation == 'created'
         uses: peter-evans/enable-pull-request-automerge@v3
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
           merge-method: squash
