name: Alena CI/CD Pipeline 

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4
      
      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Устанавливаем тестовый фреймворк
         
      - name: Запуск калькулятора +
        run: python Calc.py 5 + 4
      
      - name: Запуск калькулятора -
        run: python Calc.py 6 - 4
  
      - name: Запуск тестов
        run: pytest test_calc.py
