name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      #- dev  # Можно добавить другие ветки при необходимости
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4
      
      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Устанавливаем тестовый фреймворк
          
      #- name: Копирование calc.py в рабочую директорию
      #  run: cp https://github.com/Alenkagstr/Lab2.git/calc.py $GITHUB_WORKSPACE/

      - name: Запуск калькулятора
        run: python Calc.py 5 + 4
      
      - name: Запуск калькулятора
        run: python Calc.py 5 * 4
      
    #  - name: Запуск тестов
    #    run: pytest test_calc.py
